CREATE TABLE lista (idLista INTEGER PRIMARY KEY AUTOINCREMENT, idUsuario INTEGER NOT NULL, nombre TEXT NOT NULL);
CREATE TABLE pelicula (idMDB INTEGER NOT NULL PRIMARY KEY, titulo TEXT NOT NULL, poster TEXT NOT NULL, estreno TEXT NOT NULL, sinopsis TEXT, nota TEXT NOT NULL);
CREATE TABLE lista_pelicula (idLista INTEGER NOT NULL, idPelicula INTEGER NOT NULL, PRIMARY KEY(idLista, idPelicula));